export const TABS = {
  SEARCH_RESULTS: "SEARCH_RESULTS",
  SELECTED_PRODUCTS: "SELECTED_PRODUCTS",
  FOUND_RECIPES: "FOUND_RECIPES"
};

export const PRODUCT_VIEW_TYPES = {
  SEARCH: "SEARCH",
  SELECTED: "SELECTED"
};
